"""
Read the colour-coded operating statement and emit pl_spec.py.

Run this again whenever the colour coding changes:

    python build_pl_spec.py "path\\to\\Memphis Operating Statement - COLOR CODE.xls"

Colour meanings (as specified by the user):
    GREEN  008000  eligible for the Summary; the column it sits in fixes the basis
                   K -> compare YTD $ to YTD Budget
                   L -> compare YTD % to YTD Budget %
                   M -> compare YTD POR to YTD Budget POR
    RED    FF0000  show on the department tab, never flag on the Summary
    PURPLE 800080  combine these lines into one, named by the note above the block
    TURQ   00CCFF  compare as a % of PAYROLL budget, not of revenue
"""
import re
import sys
from pathlib import Path

import xlrd

GREEN, RED, TURQ, PURPLE = "008000", "FF0000", "00CCFF", "800080"

# purple blocks that carry no written note - name supplied by the user
DEFAULT_GROUP = {"Administrative": "Employee Expenses"}
# tidy up spelling from the hand-written notes
RENAME = {"Resturant": "Restaurant"}
COL_YTD, COL_PCT, COL_POR = 10, 11, 12          # K, L, M
COL_BUD, COL_BUD_PCT, COL_BUD_POR = 16, 17, 18  # Q, R, S


def main(src):
    bk = xlrd.open_workbook(src, formatting_info=True)
    sh = bk.sheet_by_index(0)

    def fill(r, c):
        col = bk.colour_map.get(bk.xf_list[sh.cell_xf_index(r, c)].background.pattern_colour_index)
        if col in (None, (0, 0, 0), (255, 255, 255)):
            return None
        return "%02X%02X%02X" % col

    def txt(r, c):
        v = sh.cell_value(r, c)
        return v.strip() if isinstance(v, str) else v

    spec, groups = {}, {}
    page = section = None
    seen = False
    pending_group = None          # note text sits one row above the block

    for r in range(sh.nrows):
        if txt(r, 0) == "PTD":
            page, section, seen = None, None, True
            pending_group = None          # notes never span a page
            continue
        if not seen:
            continue

        note = txt(r, COL_YTD)                       # instruction written in K
        if isinstance(note, str) and note.strip():
            low = note.lower()
            if low.startswith("combine"):
                # "combine as RESTURANT" / "Combine : Media Promotion"
                name = re.sub(r"^\s*combine\s*(as|:)?\s*", "", note, flags=re.I)
                pending_group = name.strip(" :").title()
                pending_group = RENAME.get(pending_group, pending_group)
            elif "compare to" in low:
                pending_group = None

        label = txt(r, 9)
        if not isinstance(label, str) or not label:
            continue
        k, q = sh.cell_value(r, COL_YTD), sh.cell_value(r, COL_BUD)
        if not (isinstance(k, (int, float)) or isinstance(q, (int, float))):
            if page is None:
                page = label
            section = label
            continue
        if page is None:
            page = "Summary"

        cols = {c: fill(r, c) for c in (COL_YTD, COL_PCT, COL_POR,
                                        COL_BUD, COL_BUD_PCT, COL_BUD_POR)}
        marks = set(v for v in cols.values() if v)
        key = f"{page}|{section}|{label}"

        if PURPLE in marks:
            gname = pending_group or DEFAULT_GROUP.get(page)
            if gname:
                groups.setdefault(f"{page}|{gname}", []).append(key)
                spec[key] = {"basis": "YTD", "flag": True, "group": gname}
            continue

        if TURQ in marks:
            spec[key] = {"basis": "PCT_PAYROLL", "flag": True, "group": None}
        elif GREEN in marks:
            basis = ("YTD" if cols[COL_YTD] == GREEN else
                     "PCT" if cols[COL_PCT] == GREEN else
                     "POR" if cols[COL_POR] == GREEN else "YTD")
            spec[key] = {"basis": basis, "flag": True, "group": None}
        elif RED in marks:
            spec[key] = {"basis": "YTD", "flag": False, "group": None}

    out = Path(__file__).with_name("pl_spec.py")
    with out.open("w", encoding="utf8") as f:
        f.write('"""Generated by build_pl_spec.py - do not hand-edit.\n\n'
                'basis: YTD = $ vs budget $ | PCT = % vs budget % |\n'
                '       POR = per-occupied-room vs budget POR |\n'
                '       PCT_PAYROLL = share of payroll vs budgeted share of payroll\n'
                'flag:  True  = may appear on the Summary when off by the threshold\n'
                '       False = shown on its tab but never flagged\n'
                'group: combine this line with the others carrying the same name\n"""\n\n')
        f.write("SPEC = {\n")
        for k in sorted(spec):
            v = spec[k]
            f.write(f"    {k!r}: {v!r},\n")
        f.write("}\n\nGROUPS = {\n")
        for k in sorted(groups):
            f.write(f"    {k!r}: {groups[k]!r},\n")
        f.write("}\n")

    flagged = sum(1 for v in spec.values() if v["flag"])
    print(f"wrote {out.name}")
    print(f"  {len(spec)} lines specified  ({flagged} flaggable, "
          f"{len(spec)-flagged} show-only)")
    from collections import Counter
    print("  bases:", dict(Counter(v["basis"] for v in spec.values())))
    print(f"  {len(groups)} combined groups:")
    for g, members in groups.items():
        print(f"     {g.split('|')[-1]}  <- {len(members)} lines")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else
         r"C:\Users\linchristemp\Downloads\Memphis Operating Statement - COLOR CODE.xls")
