"""
Hotel P&L Builder
=================

Reads a folder of Operating Statement .xls exports and builds one formatted
Excel P&L workbook per hotel, showing Actual vs Budget vs Projected for every
year you have a statement for, with large variances highlighted.

    python hotel_pl_tool.py --input "C:\\path\\to\\statements" --output "C:\\path\\out"

One source file = one hotel, one year. The year and hotel name are read out of
the report header, so files can be named anything.

Notes on the source format (fixed layout, column J holds the line-item label):
    A  PTD actual        G  PTD budget
    K  YTD actual        Q  YTD budget        N  YTD last year
The YTD-last-year column is unreliable in these exports (it repeats the PTD
value), so history is built from separate annual files instead.
"""
from __future__ import annotations

import argparse
import io
import re
import sys
import zipfile
from collections import OrderedDict, defaultdict
from pathlib import Path

import xlrd
from openpyxl import Workbook
from openpyxl.formatting.rule import FormulaRule
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter as gcl

# --------------------------------------------------------------------------
# configuration
# --------------------------------------------------------------------------
# bump this whenever the output format changes - the app shows it, so you
# can tell at a glance whether Streamlit Cloud is running the new build
__version__ = "2026-08-12 · CC palette, per-tab charts, hidden feed"

try:                                     # generated by build_pl_spec.py
    from pl_spec import SPEC, GROUPS
except ImportError:                       # tool still works with no colour spec
    SPEC, GROUPS = {}, {}

FLAG_PCT = 0.10          # a green line lands on the Summary when it is this far off

MAX_YEARS = 10                  # keep at most this many years, most recent first
VAR_PCT = 0.10                  # flag when |actual-budget| / budget exceeds this
VAR_MIN = 5000                  # ...and the dollar swing exceeds this

COL_LABEL = 9                   # J
COL_PTD_ACT, COL_PTD_BUD = 0, 6         # A, G
COL_YTD_ACT, COL_YTD_BUD, COL_YTD_LY = 10, 16, 13   # K, Q, N
COL_YTD_PCT, COL_BUD_PCT = 11, 17                   # L, R  - % of revenue
COL_YTD_POR, COL_BUD_POR = 12, 18                   # M, S  - per occupied room

# page title (as it appears in the statement)  ->  output tab
TAB_MAP = OrderedDict([
    ("Rooms Department",      "Rooms"),
    ("Food Department",       "Food"),
    ("Beverage Department",   "Beverage"),
    ("Spa",                   "Miscellaneous"),
    ("Miscellaneous Revenue", "Miscellaneous"),
    ("Rental Income",         "Miscellaneous"),
    ("Administrative",          "Undistributed"),
    ("IT Systems",              "Undistributed"),
    ("Advertising & Promotions", "Undistributed"),
    ("Franchise Fees",          "Undistributed"),
    ("Utilities",               "Undistributed"),
    ("Repairs & Maintenance",   "Undistributed"),
    ("Laundry Department",      "Undistributed"),
    ("Payroll Taxes & Benefits", "Undistributed"),
])

# lines pulled onto the Fixed Expenses tab (matched case-insensitively)
FIXED_LINES = ["Real Estates Taxes", "Real Estate Taxes", "Insurance", "Leases"]

# Summary tab, grouped. Every line comes off the statement's own Summary page.
SUMMARY_GROUPS = [
    ("REVENUE", ["Room", "Food & Beverage", "Spa Revenue", "Miscellaneous",
                 "Rental Income", "Total Revenue"]),
    ("EXPENSES", ["Total Departmental Expenses", "Total Undistributed Expenses",
                  "Non-Operating Expenses", "Total Non-OperatingExpenses"]),
    ("PROFIT", ["Total Department Profit or Loss", "Operating Profit or Loss",
                "Net Income or Loss"]),
    ("OPERATING STATISTICS", ["Rooms Available", "Rooms Sold", "A.D.R.",
                              "Occupancy", "REV PAR"]),
]
SUMMARY_LINES = [l for _, g in SUMMARY_GROUPS for l in g]
RATIO_LINES = {"a.d.r.", "occupancy", "rev par"}   # not dollars

# --------------------------------------------------------------------------
# styling
# --------------------------------------------------------------------------
FONT = "Calibri"
# palette read straight out of "Hilton Memphis - P&L (7) - CC.xlsx"
# (theme colours with their tints resolved to flat RGB)
NAVY = "17375E"        # dk2 -25%   section bands + column headers
TEAL = "93CDDD"        # accent5 +40%  total-row label
PALE = "DCE6F2"        # accent1 +80%  total-row figures
INK, WHITE, GREEN, MUTED = "000000", "FFFFFF", "14532D", "6B6B6B"

F_TITLE = Font(name=FONT, size=14, color=INK)
F_YEAR = Font(name=FONT, size=12, color=WHITE)
F_HDR = Font(name=FONT, size=12, color=WHITE)
F_SECT = Font(name=FONT, size=11, color=WHITE)
F_LBL = Font(name=FONT, size=11, color=INK)
F_TOT = Font(name=FONT, size=11, bold=True, color=INK)      # total figures
F_TOTL = Font(name=FONT, size=12, bold=True, color=INK)     # total label
F_NOTE = Font(name=FONT, size=9, italic=True, color=MUTED)

FILL_NAVY = PatternFill("solid", fgColor=NAVY)
FILL_TEAL = PatternFill("solid", fgColor=TEAL)
FILL_PALE = PatternFill("solid", fgColor=PALE)
# Conditional formatting uses DIFFERENTIAL formats, and Excel takes a dxf solid
# fill's colour from bgColor, not fgColor. openpyxl writes only fgColor, which
# makes Excel paint the cell solid WHITE - covering the gridlines. Setting both
# start_color and end_color emits fgColor AND bgColor, so it renders correctly.
FILL_BAD = PatternFill(start_color="F8D2D2", end_color="F8D2D2", fill_type="solid")
FILL_GOOD = PatternFill(start_color="D8EDDF", end_color="D8EDDF", fill_type="solid")

# accounting format, exactly as in the CC file - no borders anywhere in this design
MONEY = r'_("$"* #,##0_);_("$"* \(#,##0\);_("$"* "-"??_);_(@_)'
RATIO = r'_("$"* #,##0.00_);_("$"* \(#,##0.00\);_("$"* "-"??_);_(@_)'
PCT = '0.0%'
COUNT = '#,##0'
COUNT_LINES = {"rooms available", "rooms sold"}
PCT_LINES = {"occupancy"}
W_LABEL, W_DATA = 46.3, 13

# each year is three sections of two columns, matching the operating statement:
#   YTD $  |  % of revenue  |  per occupied room     (Actual and Budget in each)
SECTIONS = [("YTD", MONEY), ("%", PCT), ("YTD POR", RATIO)]
COLS_PER_YEAR = 6
H_TITLE, H_BAND = 18.75, 15.75


# --------------------------------------------------------------------------
# parsing
# --------------------------------------------------------------------------
class Line:
    __slots__ = ("page", "section", "label", "act", "bud",
                 "pct", "bpct", "por", "bpor", "is_total")

    def __init__(self, page, section, label, act, bud, is_total,
                 pct=0.0, bpct=0.0, por=0.0, bpor=0.0):
        self.page, self.section, self.label = page, section, label
        self.act, self.bud, self.is_total = act, bud, is_total
        self.pct, self.bpct, self.por, self.bpor = pct, bpct, por, bpor

    @property
    def key(self):
        return (self.page, self.section, self.label)

    @property
    def spec_key(self):
        return f"{self.page}|{self.section}|{self.label}"

    @property
    def vals(self):
        return (self.act, self.bud, self.pct, self.bpct, self.por, self.bpor)


def _txt(sheet, r, c):
    try:
        v = sheet.cell_value(r, c)
    except IndexError:
        return ""
    return v.strip() if isinstance(v, str) else v


def _num(sheet, r, c):
    try:
        v = sheet.cell_value(r, c)
    except IndexError:
        return None
    return float(v) if isinstance(v, (int, float)) and not isinstance(v, bool) else None


def parse_statement(path=None, *, data: bytes = None, name: str = ""):
    """-> (hotel, year, [Line, ...], (month, day))  from a path or raw .xls bytes.

    The 4th value is the statement's "As of" month/day. If someone uploads twelve
    monthly exports for one year they all carry the same year, so the caller keeps
    whichever has the latest as-of date - that is the most complete YTD."""
    if data is not None:
        book = xlrd.open_workbook(file_contents=data)
        path = Path(name or "uploaded.xls")
    else:
        book = xlrd.open_workbook(str(path), on_demand=False)
    sh = book.sheet_by_index(0)

    # The header block is not always in the same column - Memphis puts it in G,
    # Myrtle Beach in F - so scan every column of the first few rows.
    hotel, year, asof = None, None, (0, 0)
    fallback = None
    for r in range(min(sh.nrows, 12)):
        for c in range(sh.ncols):
            g = _txt(sh, r, c)
            if not isinstance(g, str) or not g:
                continue
            if "Property:" in g:
                name = g.split("Property:")[-1].strip()
                if "Operating" in g and hotel is None:
                    hotel = name                    # the operating entity names the hotel
                elif fallback is None:
                    fallback = name
            m = re.search(r"As of\s+(\d{1,2})/(\d{1,2})/(\d{4})", g)
            if m:
                asof = (int(m.group(1)), int(m.group(2)))
                year = int(m.group(3))
    if hotel is None:
        hotel = fallback
    if hotel is None or year is None:
        raise ValueError(f"{path.name}: could not read hotel name / year from header")
    hotel = re.sub(r"\s+", " ", hotel).strip()   # header spacing varies between exports

    lines, page_title, section = [], None, None
    seen_page_header = False
    for r in range(sh.nrows):
        if str(_txt(sh, r, 0)) == "PTD":          # column-header row = new page
            page_title, section, seen_page_header = None, None, True
            continue
        if not seen_page_header:
            continue
        label = _txt(sh, r, COL_LABEL)
        if not isinstance(label, str) or not label:
            continue
        act = _num(sh, r, COL_YTD_ACT)
        bud = _num(sh, r, COL_YTD_BUD)
        if act is None and bud is None:           # a heading, not a data row
            if page_title is None:
                page_title = label
            section = label
            continue
        if page_title is None:
            page_title = "Summary"
        low = label.lower()
        lines.append(Line(
            page_title, section or page_title, label, act or 0.0, bud or 0.0,
            low.startswith("total") or "profit or loss" in low
            or low.startswith("net income"),
            _num(sh, r, COL_YTD_PCT) or 0.0, _num(sh, r, COL_BUD_PCT) or 0.0,
            _num(sh, r, COL_YTD_POR) or 0.0, _num(sh, r, COL_BUD_POR) or 0.0))
    return hotel, year, lines, asof


# --------------------------------------------------------------------------
# workbook writing
# --------------------------------------------------------------------------
def _year_header(ws, years, start_row, first_col=2):
    """Three header rows: the year, then YTD / % / YTD POR, then Actual|Budget."""
    for rr in (start_row, start_row + 1, start_row + 2):
        ws.row_dimensions[rr].height = H_BAND
        ws.cell(row=rr, column=1).fill = FILL_NAVY
    for i, yr in enumerate(years):
        y0 = first_col + i * COLS_PER_YEAR
        ws.merge_cells(start_row=start_row, start_column=y0,
                       end_row=start_row, end_column=y0 + COLS_PER_YEAR - 1)
        for j in range(COLS_PER_YEAR):
            ws.cell(row=start_row, column=y0 + j).fill = FILL_NAVY
        yc = ws.cell(row=start_row, column=y0, value=yr)
        yc.font, yc.fill = F_YEAR, FILL_NAVY
        yc.alignment = Alignment(horizontal="center")
        yc.number_format = '0'

        for k, (name, _fmt) in enumerate(SECTIONS):
            c0 = y0 + k * 2
            ws.merge_cells(start_row=start_row + 1, start_column=c0,
                           end_row=start_row + 1, end_column=c0 + 1)
            for j in (0, 1):
                ws.cell(row=start_row + 1, column=c0 + j).fill = FILL_NAVY
            sc = ws.cell(row=start_row + 1, column=c0, value=name)
            sc.font, sc.fill = F_HDR, FILL_NAVY
            sc.alignment = Alignment(horizontal="center")
            for j, h in enumerate(("Actual", "Budget")):
                hc = ws.cell(row=start_row + 2, column=c0 + j, value=h)
                hc.font, hc.fill = F_HDR, FILL_NAVY
                hc.alignment = Alignment(horizontal="right")
                ws.column_dimensions[gcl(c0 + j)].width = W_DATA


def _write_grid(ws, rows, years, data, start_row, first_col=2, at=None,
                rowmap=None):
    """rows: (key, label, is_total). Each year gets YTD $, % and POR, Actual+Budget."""
    r = start_row
    for key, label, is_total in rows:
        if key is None:                                   # section band
            c = ws.cell(row=r, column=1, value=label)
            c.font, c.fill = F_SECT, FILL_NAVY
            r += 1
            continue
        low = label.strip().lower()
        ytd_fmt = (PCT if low in PCT_LINES else COUNT if low in COUNT_LINES
                   else RATIO if low in RATIO_LINES else MONEY)
        lc = ws.cell(row=r, column=1, value=label)
        if is_total:
            lc.font, lc.fill = F_TOTL, FILL_TEAL
            ws.row_dimensions[r].height = H_BAND
        else:
            lc.font = F_LBL
        for i, yr in enumerate(years):
            y0 = first_col + i * COLS_PER_YEAR
            vals = data.get(yr, {}).get(key, (0.0,) * 6)   # act,bud,pct,bpct,por,bpor
            for j in range(6):
                cell = ws.cell(row=r, column=y0 + j, value=vals[j])
                sec = j // 2
                cell.number_format = ytd_fmt if sec == 0 else SECTIONS[sec][1]
                cell.font = F_TOT if is_total else F_LBL
                if is_total:
                    cell.fill = FILL_PALE
        if at is not None:
            at.setdefault(low, r)
        if rowmap is not None:
            rowmap.append((r, key))
        r += 1
    return r


def _apply_flag_rules(ws, years, rowmap, order, first_col=2, threshold=FLAG_PCT):
    """Shade the Actual cell when a green-marked line is off budget.

    Only the section its colour nominated is shaded - a line marked green in the
    % column is judged on %, not on dollars. PCT_PAYROLL lines need total payroll
    to evaluate, so they are flagged on the Summary instead.
    """
    SEC = {"YTD": 0, "PCT": 1, "POR": 2}
    buckets = {}
    for row, key in rowmap:
        ln = order.get(key)
        sp = SPEC.get(ln.spec_key) if ln is not None else None
        if not sp or not sp["flag"]:
            continue
        sec = SEC.get(sp["basis"])
        if sec is None:
            continue
        for i in range(len(years)):
            buckets.setdefault((i, sec), []).append(row)

    for (i, sec), rowlist in buckets.items():
        c0 = first_col + i * COLS_PER_YEAR + sec * 2
        act, bud = gcl(c0), gcl(c0 + 1)
        rowlist.sort()
        anchor = rowlist[0]
        sqref = " ".join(f"{act}{r}" for r in rowlist)
        base = (f'AND(${bud}{anchor}<>0,'
                f'ABS((${act}{anchor}-${bud}{anchor})/${bud}{anchor})>{threshold}')
        ws.conditional_formatting.add(
            sqref, FormulaRule(formula=[base + f',${act}{anchor}>${bud}{anchor})'],
                               fill=FILL_BAD))
        ws.conditional_formatting.add(
            sqref, FormulaRule(formula=[base + f',${act}{anchor}<${bud}{anchor})'],
                               fill=FILL_GOOD))


def _off_budget(basis, vals, payroll):
    """-> (actual, budget, fraction_off) on the given basis, or None.

    payroll is (total salaries actual, total salaries budget), used only by the
    PCT_PAYROLL basis where a line is judged as a share of payroll rather than
    of revenue.
    """
    act, bud, pct, bpct, por, bpor = vals
    if basis == "PCT":
        a, b = pct, bpct
    elif basis == "POR":
        a, b = por, bpor
    elif basis == "PCT_PAYROLL":
        pa, pb = payroll
        a = act / pa if pa else 0.0
        b = bud / pb if pb else 0.0
    else:
        a, b = act, bud
    if not b:
        return None
    return a, b, (a - b) / b


BASIS_LABEL = {"YTD": "$ vs budget", "PCT": "% of revenue",
               "POR": "per occupied room", "PCT_PAYROLL": "% of payroll"}


def _combine_groups(items, data, years):
    """Fold each purple group into a single line, in place of its first member."""
    if not GROUPS:
        return items
    member_of, order = {}, {}
    for gkey, members in GROUPS.items():
        page, name = gkey.split("|", 1)
        for m in members:
            member_of[m] = (page, name)
        order[(page, name)] = members
    out, placed = [], set()
    for key, ln in items:
        g = member_of.get(ln.spec_key)
        if g is None:
            out.append((key, ln))
            continue
        if g in placed:
            continue                      # already emitted the combined line
        placed.add(g)
        page, name = g
        gkey = ("__group__", page, name)
        for yr in years:
            tot = [0.0] * 6
            for m in order[g]:
                for k2, l2 in items:
                    if l2.spec_key == m:
                        v = data.get(yr, {}).get(k2, (0.0,) * 6)
                        for i in (0, 1):          # dollars add up; % and POR do not
                            tot[i] += v[i]
            data.setdefault(yr, {})[gkey] = tuple(tot)
        combined = Line(page, ln.section, name, 0.0, 0.0, False)
        out.append((gkey, combined))
    return out



def _off_budget_block(ws, start_row, years, data, order, threshold=FLAG_PCT):
    """Summary section: every green line more than `threshold` off budget.

    Judged on the latest year, each line on the basis its colour specified.
    """
    yr = years[-1]
    payroll = (0.0, 0.0)
    for key, ln in order.items():
        if ln.page == "Summary" and ln.label.lower() == "total salaries":
            v = data.get(yr, {}).get(key, (0.0,) * 6)
            payroll = (v[0], v[1])
            break

    hits = []
    for key, ln in order.items():
        sp = SPEC.get(ln.spec_key)
        if not sp or not sp["flag"]:
            continue
        res = _off_budget(sp["basis"], data.get(yr, {}).get(key, (0.0,) * 6), payroll)
        if res is None:
            continue
        a, b, frac = res
        if abs(frac) > threshold:
            hits.append((ln.page, ln.label, sp["basis"], a, b, frac))
    hits.sort(key=lambda h: (h[0], -abs(h[5])))

    r = start_row
    c = ws.cell(row=r, column=1,
                value=f"ITEMS MORE THAN {threshold:.0%} OFF BUDGET   ({yr})")
    c.font, c.fill = F_SECT, FILL_NAVY
    r += 1
    for j, h in enumerate(["Category", "Line item", "Compared on",
                           "Actual", "Budget", "Off by"]):
        hc = ws.cell(row=r, column=1 + j, value=h)
        hc.font, hc.fill = F_HDR, FILL_NAVY
    r += 1
    if not hits:
        ws.cell(row=r, column=1, value="Nothing outside the threshold.").font = F_LBL
        return r + 1
    for page, label, basis, a, b, frac in hits:
        ws.cell(row=r, column=1, value=page).font = F_LBL
        ws.cell(row=r, column=2, value=label).font = F_LBL
        ws.cell(row=r, column=3, value=BASIS_LABEL.get(basis, basis)).font = F_LBL
        fmt = PCT if basis in ("PCT", "PCT_PAYROLL") else MONEY
        for col, val in ((4, a), (5, b)):
            cc = ws.cell(row=r, column=col, value=val)
            cc.number_format, cc.font = fmt, F_LBL
        oc = ws.cell(row=r, column=6, value=frac)
        oc.number_format, oc.font = '0.0%', F_TOT
        oc.fill = FILL_BAD if frac > 0 else FILL_GOOD
        r += 1
    return r



def _fix_styles(raw: bytes) -> bytes:
    """Repair what openpyxl gets wrong in the saved file.

    1. Default fill is written as a bare <patternFill/> with no patternType.
       Excel then paints those cells solid white, over the gridlines.
    2. Six-digit colours are padded to 00RRGGBB - a transparent alpha channel.
    3. Empty cells are tagged t="n" (numeric) with no value.
    4. Differential (conditional-format) fills need bgColor, not just fgColor,
       or Excel renders the highlight as white.
    """
    zin = zipfile.ZipFile(io.BytesIO(raw))
    parts = {n: zin.read(n) for n in zin.namelist()}
    for name in parts:
        if name.startswith("xl/worksheets/sheet"):
            parts[name] = parts[name].decode("utf8").replace(' t="n"', "").encode("utf8")
    st = parts["xl/styles.xml"].decode("utf8")

    def _dxf_bg(m):
        block = m.group(0)
        if "bgColor" in block:
            return block
        fg = re.search(r'<fgColor rgb="([0-9A-Fa-f]{8})"', block)
        if not fg:
            return block
        return block.replace("</patternFill>",
                             '<bgColor rgb="%s"/></patternFill>' % fg.group(1))
    st = re.sub(r"<dxf>.*?</dxf>", _dxf_bg, st, flags=re.S)
    st = re.sub(r"<patternFill\s*/>", '<patternFill patternType="none"/>', st)
    st = re.sub(r'rgb="00([0-9A-Fa-f]{6})"',
                lambda m: 'rgb="FF%s"' % m.group(1), st)
    parts["xl/styles.xml"] = st.encode("utf8")
    out = io.BytesIO()
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zo:
        for n in zin.namelist():
            zo.writestr(n, parts[n])
    return out.getvalue()


def _sheet_header(ws, hotel, title):
    ws["A1"] = f"{hotel}  -  {title}"
    ws["A1"].font = F_TITLE
    ws.row_dimensions[1].height = H_TITLE
    ws.column_dimensions["A"].width = W_LABEL
    ws.sheet_view.showGridLines = True


def build_workbook(hotel, per_year, out_path: Path, sources=None):
    # only the years we actually have a statement for - never zero-filled,
    # capped at the most recent MAX_YEARS
    years = sorted(per_year)
    span = years[-MAX_YEARS:]

    data = defaultdict(dict)
    order = OrderedDict()          # key -> (page, section, label, is_total)
    for yr in years:
        for ln in per_year[yr]:
            data[yr][ln.key] = ln.vals
            order.setdefault(ln.key, ln)

    wb = Workbook()
    wb.remove(wb.active)

    # ---- Summary ---------------------------------------------------------
    ws = wb.create_sheet("Summary")
    _sheet_header(ws, hotel, "SUMMARY")
    _year_header(ws, span, 4)
    rows, used = [], set()
    for heading, labels in SUMMARY_GROUPS:
        rows.append((None, heading, False))
        for name in labels:
            for key, ln in order.items():
                if (ln.page == "Summary" and key not in used
                        and ln.label.lower() == name.lower()):
                    rows.append((key, ln.label, ln.is_total))
                    used.add(key)
                    break
    at, rmap = {}, []
    end = _write_grid(ws, rows, span, data, 7, at=at, rowmap=rmap)
    _apply_flag_rules(ws, span, rmap, order)
    

    # margins, computed off the rows just written
    mc = ws.cell(row=end + 1, column=1, value="MARGINS")
    mc.font, mc.fill = F_SECT, FILL_NAVY
    rev, op, ni = at.get("total revenue"), at.get("operating profit or loss"),         at.get("net income or loss")
    for k, (lab, src) in enumerate([("Operating Profit Margin", op),
                                    ("Net Income Margin", ni)]):
        r = end + 2 + k
        ws.cell(row=r, column=1, value=lab).font = F_LBL
        if not (src and rev):
            continue
        for i in range(len(span)):
            for j in (0, 1):                       # actual and budget columns
                c = gcl(2 + i * 4 + j)
                cell = ws.cell(row=r, column=2 + i * 4 + j,
                               value=f'=IF({c}{rev}=0,"",{c}{src}/{c}{rev})')
                cell.number_format, cell.font = '0.0%', F_LBL
    ws.freeze_panes = "A7"
    _off_budget_block(ws, end + 2, span, data, order)

    # ---- department tabs -------------------------------------------------
    tabs = OrderedDict()
    for key, ln in order.items():
        tab = TAB_MAP.get(ln.page)
        if tab:
            tabs.setdefault(tab, []).append((key, ln))
    for tab in ["Rooms", "Food", "Beverage", "Miscellaneous", "Undistributed"]:
        items = tabs.get(tab, [])
        ws = wb.create_sheet(tab)
        _sheet_header(ws, hotel, tab.upper())
        _year_header(ws, span, 4)
        items = _combine_groups(items, data, span)
        rows, cur = [], None
        for key, ln in items:
            if ln.section != cur:
                rows.append((None, ln.section, False))
                cur = ln.section
            rows.append((key, ln.label, ln.is_total))
        at_tab, rmap = {}, []
        end = _write_grid(ws, rows, span, data, 7, at=at_tab, rowmap=rmap)
        _apply_flag_rules(ws, span, rmap, order)
        
        ws.freeze_panes = "A7"

    # ---- Fixed Expenses --------------------------------------------------
    ws = wb.create_sheet("Fixed Expenses")
    _sheet_header(ws, hotel, "FIXED EXPENSES")
    _year_header(ws, span, 4)
    rows = [(None, "FIXED EXPENSES", False)]
    fx = [f.lower() for f in FIXED_LINES]
    for key, ln in order.items():
        if ln.label.lower() in fx and ln.page == "Non-Operating Expenses":
            rows.append((key, ln.label, False))
    rmap = []
    end = _write_grid(ws, rows, span, data, 7, rowmap=rmap)
    _apply_flag_rules(ws, span, rmap, order)
    tot = end
    tl = ws.cell(row=tot, column=1, value="TOTAL FIXED EXPENSES")
    tl.font, tl.fill = F_TOTL, FILL_TEAL
    ws.row_dimensions[tot].height = H_BAND
    for i in range(len(span)):
        y0 = 2 + i * COLS_PER_YEAR
        for j in range(COLS_PER_YEAR):
            col = gcl(y0 + j)
            c = ws.cell(row=tot, column=y0 + j,
                        value=f"=SUM({col}8:{col}{tot-1})")
            c.number_format = MONEY if j < 2 else SECTIONS[j // 2][1]
            c.font, c.fill = F_TOT, FILL_PALE
    
    ws.freeze_panes = "A7"

    for s in wb.worksheets:
        s.sheet_properties.tabColor = GREEN if s.title != "Summary" else "1C1C1C"
    # the chart-feed cells are formulas with no cached result; without this the
    # charts open empty until something forces a recalculation
    wb.calculation.fullCalcOnLoad = True
    tmp = io.BytesIO()
    wb.save(tmp)
    data = _fix_styles(tmp.getvalue())
    if hasattr(out_path, "write"):
        out_path.write(data)
    else:
        Path(out_path).write_bytes(data)
    return span


def main():
    ap = argparse.ArgumentParser(description="Build hotel P&L workbooks from operating statements.")
    ap.add_argument("--input", required=True, help="folder containing .xls operating statements")
    ap.add_argument("--output", default=None, help="output folder (default: alongside input)")
    a = ap.parse_args()

    src = Path(a.input)
    out = Path(a.output) if a.output else src
    out.mkdir(parents=True, exist_ok=True)

    files = sorted(p for p in src.glob("*.xls") if not p.name.startswith("~$"))
    if not files:
        sys.exit(f"no .xls files found in {src}")

    hotels = defaultdict(dict)
    srcmap = defaultdict(dict)
    asofmap = defaultdict(dict)
    for p in files:
        try:
            hotel, year, lines, asof = parse_statement(p)
        except Exception as e:                                  # noqa: BLE001
            print(f"  SKIPPED {p.name}: {e}")
            continue
        prev = asofmap[hotel].get(year)
        if prev is not None and prev >= asof:
            print(f"  read {p.name:52} -> {hotel} {year} (older as-of, ignored)")
            continue
        hotels[hotel][year] = lines
        srcmap[hotel][year] = p.name
        asofmap[hotel][year] = asof
        print(f"  read {p.name:52} -> {hotel} {year} ({len(lines)} lines)")

    for hotel, per_year in hotels.items():
        safe = re.sub(r"[^\w\- ]", "", hotel).strip() or "Hotel"
        dest = out / f"{safe} - P&L.xlsx"
        span = build_workbook(hotel, per_year, dest, srcmap[hotel])
        print(f"\n{hotel}: {len(span)} year(s)  ->  {dest.name}")
        print(f"  years included : {span}")


if __name__ == "__main__":
    main()
